# This is my first, very own configuration file for yamllint!
# It extends the default conf by adjusting some options.

extends: default

ignore: |
  node_modules/

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 400
    level: warning
  document-start: disable
  truthy: {check-keys: false}  # flags the `on` values in GitHub Action workflows
