---

id: futureProject

formGroups:
  - preset: adminCode
  - preset: empty
    title: projects
    param: {start: true}
  - preset: selectFutureProject
  - preset: team
  - preset: description
  - preset: category
  - preset: contact
  - preset: dates
    param: {created: true, closed: true}
  - preset: partners
  - preset: empty
