name: Validate YAML files

on:
  push:
    paths:
      - "requirements.txt"
      - ".yamllint.yaml"
      - "**/*.yml"
      - "**/*.yaml"
    branches-ignore:
      - "dependabot/**"
  pull_request:
    paths:
      - "requirements.txt"
      - ".yamllint.yaml"
      - "**/*.yml"
      - "**/*.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate YAML schemas
        run: |
          yamale -s schemaCode.yaml _data/code
          yamale -s schemaAdmin.yaml _data/administrations
          yamale -s schemaSoftware.yaml _data/software
          yamale -s schemaStandard.yaml _data/standard
          yamale -s schemaPartnership.yaml _data/partnership

      - name: Lint Yaml
        run: yamllint .
