name: Mirror Content to French repo

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "CNAME"
      - ".github/"
      - "!.github/workflows/sync-french.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'canada-ca'

    steps:
      - name: Checkout Main repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: english
          submodules: true
      - name: Checkout French mirror
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: canada-ca/ore-ero-fr
          path: french
          ref: master
          token: ${{ secrets.PUSH_API_TOKEN }}
          submodules: true
      - name: Copy files from English to French
        run: rsync -avr --delete --exclude=*.git/* --exclude=*.github/* --exclude='*CNAME' --exclude='*_data/spdx' english/ french
      - name: Sync SPDX submodule
        working-directory: french/_data/spdx
        run: |
          git fetch --unshallow --all 2>/dev/null || git fetch --all
          git checkout $(cat ../../../english/.git/modules/_data/spdx/HEAD)
      - name: Push back changes to French repo
        working-directory: french
        run: |
          git config --global user.email "canada.pr.bot@gmail.com"
          git config --global user.name "canada-bot"
          git add -A
          git commit -m "Sync Action" || true
          git push
